export const ENTITIES = {
  floorLamp:      'light.wiz_rgbw_tunable_4e39dc',
  harryPotter:    'input_boolean.harry_potter_house_light',
  cafeHouse:      'input_boolean.cafe_house_light',
  spaceProjector: 'button.bf8f2fiq3ny50q3h_push',
  birdsLight:     'remote.chuangmi_v2_9dae_ir',
};

export const SCRIPTS = {
  harryOn:  'script.harry_potter_haus_einschalten',
  harryOff: 'script.harry_potter_haus_ausschalten',
  cafeOn:   'script.cafe_potter_haus_einschalten',
  cafeOff:  'script.cafe_haus_ausschalten',
};

export const LAMP_PRESETS = [
  { id: 'dim',    label: 'Dim',    brightness: 25,  kelvin: 2200 },
  { id: 'warm',   label: 'Warm',   brightness: 153, kelvin: 2700 },
  { id: 'bright', label: 'Bright', brightness: 255, kelvin: 4000 },
  { id: 'cool',   label: 'Cool',   brightness: 255, kelvin: 6500 },
];

export const IR_CODES = {
  off:     'Z6VLADkCAABrBgAAqggAAHARAAA6IwAA6JkAAOBzAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0AAAAAAAAAAAQEBAQEBAQEBAQEAAAABAAAAAAEBAQABBQJGAkAA==',
  on:      'Z6VHADQCAAB2BgAAxggAAHIRAAAZIwAANiMAAOiZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1AAAAAAAAAAAQEBAQEBAQEBAAEAAAABAAABAAEBAQABBgJAA=',
  steady:  'Z6VHADcCAABuBgAAqAgAAGsRAAA0IwAA6JkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0AAAAAAAAAAAQEBAQEBAQEAAQEBAQABAAEAAAAAAQABBQJAA=',
  mode1:   'Z6VHAB0CAABJAgAAkAYAAMkIAACOEQAAGSMAAEyaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFEBAQEBAQEBAgICAgICAgIBAQIBAQECAQICAQICAgECBgNQA=',
  mode2:   'Z6VHAB4CAABHAgAAjwYAAMcIAACMEQAAFiMAAEyaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFEBAQEBAQEBAgICAgICAgICAgEBAQECAQEBAgICAgECBgNQA=',
  mode3:   'Z6VHAB0CAABIAgAAkAYAAMgIAACNEQAAFSMAAEyaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFEBAQEBAQEBAgICAgICAgICAgIBAQEBAQEBAQICAgICBgNQA=',
  mode4:   'Z6VHAB0CAABJAgAAkQYAAMkIAACPEQAAGyMAAEyaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFEBAQEBAQEBAgICAgICAgICAQECAQEBAQECAgECAgICBgNQA=',
  mode5:   'Z6VHAB0CAABIAgAAjwYAAMcIAACJEQAAEyMAAOiZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFEBAQEBAQEBAgICAgICAgIBAgIBAgEBAQIBAQIBAgICBgNQA=',
  mode6:   'Z6VHAB0CAABJAgAAkAYAAMgIAACNEQAAGCMAAEyaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFEBAQEBAQEBAgICAgICAgICAQICAQEBAQECAQECAgICBgNQA=',
  mode7:   'Z6VHAC0CAACKBgAAxAgAAIkRAAAcIwAA6JkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0AAAAAAAAAAAQEBAQEBAQEAAAEBAAAAAAEBAAABAQEBBQJAA=',
  dimDown: 'Z6VHAB4CAABIAgAAjwYAAMcIAACLEQAAFiMAAEyaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFEBAQEBAQEBAgICAgICAgIBAQECAQEBAQICAgECAgICBgNQA=',
  dimUp:   'Z6VHACACAABGAgAAjQYAAMcIAACJEQAAGCMAAEyaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFEBAQEBAQEBAgICAgICAgIBAgECAgECAQIBAgEBAgECBgNQA=',
};